require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
Style/BlockDelimiters:
  EnforcedStyle: semantic
  Exclude:
    - spec/factories/**/*
Style/Documentation:
  Enabled: false
