version: '3.8'

services:
  postgres:
    image: postgres:14.1
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    env_file: .env
    command: bash -c 'rm tmp/pids/server.pid 2>/dev/null; bin/rails s -b "0.0.0.0"'
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
      - bundle_cache:/usr/local/bundle
volumes:
  bundle_cache:
  postgres_data:
